export const CATEGORY_SUBCATEGORY_MAP = {
  Sport: [
    'Waterbottle',
    'Outdoor trousers',
    'Garment Set',
    'Sandals',
    'Gloves',
    'Outdoor Waistcoat',
    'Hair string',
    'Tailored Waistcoat',
    'Bikini top',
    'Hat/beanie',
    'Cap/peaked',
    'Bag',
    'Trousers',
    'Underwear bottom',
    'Scarf',
    'Sarong',
    'Swimwear bottom',
    'Long John',
    'T-shirt',
    'Shorts',
    'Hoodie',
    'Sweater',
    'Socks',
    'Unknown',
    'Swimsuit',
    'Other accessories',
    'Vest top',
    'Jacket',
    'Top',
    'Giftbox',
    'Bra',
    'Leggings/Tights',
    'Skirt',
  ],
  Ladieswear: [
    'Top',
    'Camisole',
    'Dress',
    'Robe',
    'One-shoulder',
    'Athletic shirt',
    'Bracelet',
    'Sewing kit',
    'Boots',
    'Night gown',
    'Hair string',
    'Crop top',
    'Hair/alice band',
    'Strapless top',
    'Long sleeve bodysuit',
    'Dog wear',
    'Sandals',
    'Underwear set',
    'Underwear corset',
    'Outdoor trousers',
    'Alice band',
    'Sweater',
    'Long-sleeve top',
    'Long sleeve tee',
    'Jumpsuit/Playsuit',
    'Umbrella',
    'Polo shirt',
    'Shorts',
    'Underwear Tights',
    'Sunglasses',
    'Athletic top',
    'Bikini top',
    'Bootie',
    'Earrings',
    'Necklace',
    'Hat/beanie',
    'Heeled sandals',
    'Maternity top',
    'Sleeveless blouse',
    'Leggings/Tights',
    'Cross-body bag',
    'Pullover',
    'Sports jersey',
    'Coat',
    'Zipper head',
    'Pumps',
    'Heels',
    'Underdress',
    'Tunic',
    'Garment Set',
    'Tee',
    'Flat shoe',
    'Activewear',
    'Flat shoes',
    'Costumes',
    'Bra',
    'Underwear body',
    'Other accessories',
    'Headband',
    'Sleeveless',
    'Long sleeve',
    'One-piece',
    'Blouse',
    'Unknown',
    'Watch',
    'Sleeveless t-shirt',
    'Dog Wear',
    'Side table',
    'Marker pen',
    'Casual top',
    'Lingerie',
    'Button-up shirt',
    'Swimsuit',
    'Hat/brim',
    'Pyjama bottom',
    'Slippers',
    'Long-sleeve blouse',
    'Clothing mist',
    'Skirt',
    'Sneakers',
    'Cardigan',
    'Hairband',
    'Socks',
    'Knitwear',
    'Ballerinas',
    'Knit top',
    'Cap/peaked',
    'Sarong',
    'Other shoe',
    'Flip flop',
    'Turtleneck',
    'Long sleeve t-shirt',
    'Wood balls',
    'Shirt',
    'Ring',
    'Jacket',
    'Short sleeve blouse',
    'Long sleeve top',
    'Tailored Waistcoat',
    'Earring',
    'Hair ties',
    'Long sleeve blouse',
    'Long-sleeve top',
    '3/4 sleeve shirt',
    'Tube top',
    'Crop top and skirt',
    'Pyjama set',
    'T-shirt',
    'Polo',
    'Gloves',
    'One-piece swimsuit',
    'Sleeveless top',
    'Trousers',
    'Sleeveless shirt',
    'Sports bra',
    'Outdoor Waistcoat',
    'Short sleeve top',
    'Short sleeve shirt',
    'Pyjama jumpsuit/playsuit',
    'Long sleeve shirt',
    'Beanie',
    'Shift dress',
    'Underwear bottom',
    'Bag',
    'Bodysuit',
    'Hoodie',
    'Long-sleeve',
    'Bustier',
    'Sweatshirt',
    'Swimwear bottom',
    'Blazer',
    'Wireless earphone case',
    'Sports apparel',
    'Nipple covers',
    'Wedge',
    'Bralette',
    'Washing bag',
    'Mobile case',
    'Stain remover spray',
    'Swimwear set',
    'Sleeveless tank',
    'Wallet',
    'Athletic tee',
    'Long-sleeve t-shirt',
    'Swimwear',
    'Long-sleeve shirt',
    'Scarf',
    'Bra extender',
    'Tank',
    'Long sleeved shirt',
    'T-shirt',
    'Underwear',
    'Belt',
    'Felt hat',
    'Hair clip',
    'Tank top',
    'Vest top',
    'Dungarees',
  ],
  Divided: [
    'Sweater',
    'Straw hat',
    'Hat/beanie',
    'Beanie',
    'Outdoor Waistcoat',
    'Skirt',
    'Wallet',
    'Underwear Tights',
    'Bracelet',
    'Shirt',
    'Bikini top',
    'Dungarees',
    'Underwear bottom',
    'Trousers',
    'Swimsuit',
    'T-shirt',
    'Swimwear set',
    'Outdoor trousers',
    'Polo shirt',
    'Tote bag',
    'Weekend/Gym bag',
    'Hair ties',
    'Bra',
    'Sneakers',
    'Scarf',
    'Gloves',
    'Belt',
    'Pumps',
    'Coat',
    'Hoodie',
    'Other accessories',
    'Earring',
    'Boots',
    'Bodysuit',
    'Necklace',
    'Giftbox',
    'Cross-body bag',
    'Top',
    'Bucket hat',
    'Flat shoe',
    'Sunglasses',
    'Wedge',
    'Cardigan',
    'Dress',
    'Cap/peaked',
    'Tailored Waistcoat',
    'Ring',
    'Blazer',
    'Backpack',
    'Hair string',
    'Ballerinas',
    'Bag',
    'Blouse',
    'Socks',
    'Hair clip',
    'Cap',
    'Slippers',
    'Flip flop',
    'Jacket',
    'Unknown',
    'Shoulder bag',
    'Shorts',
    'Hat/brim',
    'Vest top',
    'Underwear set',
    'Leggings/Tights',
    'Jumpsuit/Playsuit',
    'Felt hat',
    'Swimwear bottom',
    'Umbrella',
    'Sandals',
    'Waterbottle',
    'Heels',
    'Hair/alice band',
  ],
  Menswear: [
    'Cross-body bag',
    'Tailored Waistcoat',
    'Bucket hat',
    'Cardigan',
    'Pyjama set',
    'Sneakers',
    'Gloves',
    'Blazer',
    'Straw hat',
    'Bra',
    'Costumes',
    'Scarf',
    'Robe',
    'Ring',
    'Jacket',
    'Jumpsuit/Playsuit',
    'Top',
    'Other accessories',
    'Cap',
    'Garment Set',
    'Socks',
    'Dungarees',
    'Bootie',
    'Shirt',
    'Underwear bottom',
    'Beanie',
    'Keychain',
    'Polo shirt',
    'Bag',
    'Flat shoes',
    'Backpack',
    'Long John',
    'Belt',
    'T-shirt',
    'Outdoor Waistcoat',
    'Boots',
    'Flip flop',
    'Pyjama bottom',
    'Braces',
    'Wallet',
    'Sunglasses',
    'Flat shoe',
    'Trousers',
    'Felt hat',
    'Hoodie',
    'Bracelet',
    'Hat/beanie',
    'Sweater',
    'Other shoe',
    'Swimwear bottom',
    'Hat/brim',
    'Giftbox',
    'Tie',
    'Unknown',
    'Shorts',
    'Coat',
    'Necklace',
    'Watch',
    'Sandals',
    'Cap/peaked',
    'Vest top',
    'Eyeglasses',
    'Earring',
    'Weekend/Gym bag',
    'Slippers',
  ],
  BabyChildren: [
    'Garment Set',
    'Outdoor Waistcoat',
    'Coat',
    'Shirt',
    'Hair/alice band',
    'Flat shoe',
    'Bodysuit',
    'Cardigan',
    'Pyjama set',
    'Accessories set',
    'Bikini top',
    'Top',
    'Underwear body',
    'Dress',
    'Socks',
    'Underwear bottom',
    'Vest top',
    'Unknown',
    'Outdoor overall',
    'Beanie',
    'Sarong',
    'Pre-walkers',
    'Necklace',
    'Swimsuit',
    'Underwear set',
    'Hair string',
    'Long John',
    'Hair clip',
    'T-shirt',
    'Sweater',
    'Outdoor trousers',
    'Bumbag',
    'Flip flop',
    'Hoodie',
    'Waterbottle',
    'Other accessories',
    'Sleeping sack',
    'Chem. cosmetics',
    'Kids Underwear top',
    'Soft Toys',
    'Moccasins',
    'Blanket',
    'Bucket hat',
    'Swimwear set',
    'Boots',
    'Polo shirt',
    'Cap',
    'Fine cosmetics',
    'Swimwear bottom',
    'Belt',
    'Pyjama bottom',
    'Dungarees',
    'Bracelet',
    'Toy',
    'Bootie',
    'Shorts',
    'Baby Bib',
    'Tie',
    'Straw hat',
    'Towel',
    'Costumes',
    'Hat/brim',
    'Blouse',
    'Sleep Bag',
    'Skirt',
    'Sneakers',
    'Cap/peaked',
    'Night gown',
    'Scarf',
    'Backpack',
    'Underwear Tights',
    'Leg warmers',
    'Pyjama jumpsuit/playsuit',
    'Bag',
    'Leggings/Tights',
    'Trousers',
    'Slippers',
    'Hat/beanie',
    'Other shoe',
    'Ballerinas',
    'Hair ties',
    'Robe',
    'Tailored Waistcoat',
    'Ring',
    'Gloves',
    'Blazer',
    'Sandals',
    'Jacket',
    'Alice band',
    'Sunglasses',
    'Swimwear top',
    'Cushion',
    'Giftbox',
    'Jumpsuit/Playsuit',
  ],
};

export const VALID_COLORS = [
  'Black',
  'Red',
  'White',
  'Grey',
  'Yellow',
  'Navy',
  'Blue',
  'Pink',
  'Green',
  'Orange',
  'Purple',
  'Aqua',
  'Lavender',
  'Fuchsia',
  'Gold',
  'Beige',
  'Teal',
  'Brown',
  'Ivory',
  'Silver',
  'Burgundy',
  'Mint',
  'Off-white',
  'Tan',
  'Peach',
  'Coral',
  'Cream',
  'Rust',
  'Mustard',
  'Bronze',
  'Copper',
  'Turquoise',
  'Rose',
  'Dusty',
  'Olive',
  'Khaki',
  'Light',
  'Dark',
  'Multi',
  'Multi-colored',
  'Yellowish',
  'Yellow-green',
  'Neon',
  'Gray',
  'Pinkish',
  'Greenish',
  'Blueish',
];

export const VALID_OCCASIONS = [
  'Casual/evening',
  'Loungewear / intimate wear',
  'Casual outings',
  'Casual/everyday',
  'Casual, evening',
  'Office/ Casual/ Formal',
  'Casual/evening wear',
  'Unknown',
  'Casual/ Office/ Outdoor',
  'Casual / evening wear',
  'Casual or evening out',
  'Casual/ Lounge',
  'Casual or evening',
  'Casual/everyday wear',
  'Casual or sporty',
  'Casual/ Office/ Sports',
  'Evening wear',
  'Casual/ Office',
  'Formal / business',
  'Nightwear',
  'Casual/ Office/ Formal',
  'Swimming',
  'Party',
  'Casual/smart casual',
  'Casual / professional',
  'Casual or party',
  'Beach/pool',
  'Casual, semi-formal',
  'Casual/seasonal',
  'Casual, party',
  'Formal events',
  'Casual/ Formal',
  'Casual/business casual',
  'Pool party',
  'Casual/fashion',
  'Casual, beach',
  'Beachwear/Pool',
  'Outdoor/ Casual/ Winter',
  'Beach',
  'Casual/ Office/ Winter',
  'Casual/ Office/ Lounge',
  'Casual/ Winter/ Office',
  'Evening/party',
  'Sports/exercise',
  'Casual/party',
  'Casual/activewear',
  'Casual/semiforma',
  'Special occasions',
  'Casual/workout',
  'Casual / night out',
  'Office/ Formal/ Evening',
  'Casual, athletic',
  'Casual/ Sports/ Lounge',
  'All occasions',
  'Office/ Formal',
  'Casual, loungewear',
  'Formal or semi-formal',
  'Depends on individual items in the set',
  'Casual/dressy',
  'Casual/ Party/ Formal',
  'Night out',
  'Casual/workwear',
  'Everyday wear',
  'Sports/activewear',
  'Casual/sports',
  'Swimming/beachwear',
  'Casual/ Formal/ Winter/ Outdoor',
  'Casual/ Formal/ Party/ Evening',
  'Casual/wear for sports',
  'Casual/ Beach/ Summer',
  'Beach/ Casual',
  'Evening event',
  'Casual / formal',
  'Formal/evening',
  'Casual/relaxed',
  'Casual/ Beach/ Outdoor',
  'Casual/ Outdoor',
  'Casual/ Office/ Party',
  'Casual/layering',
  'Sports events',
  'Casual/smart-casual',
  'Casual/ Party/ Evening',
  'Casual/active wear',
  'Casual and dressy',
  'Casual or semi-formal',
  'Party/ Event',
  'Workout / casual',
  'Casual/professional',
  'Casual wear',
  'Outdoor/ Casual',
  'Beachwear',
  'Nightwear / lingerie',
  'Casual/ Sports/ Travel',
  'Casual/office',
  'Casual/ Sports/ Beach',
  'Formal',
  'Lingerie',
  'Casual or office wear',
  'Casual / evening',
  'Casual/evening out',
  'Casual',
  'Casual/ Sports',
  'Casual',
  'Casual, activewear',
  'Casual or night out',
  'Athletic wear',
  'Casual, everyday wear',
  'Casual/ Office/ Evening',
  'Halloween',
  'Casual/business',
  'Office/ Formal/ Casual',
  'Casual or professional',
  'Casual/work',
  'Casual or dressy',
  'Casual or formal',
  'Casual or evening wear',
  'Casual/ Party',
  'Beach/ Pool',
  'Evening',
  'Casual outing',
  'Lounge/ Casual',
  'Casual / business',
  'Casual, sports',
  'Casual wear',
  'Casual / everyday wear',
  'Casual to semi-formal',
];

export const VALID_MATERIALS = [
  'Cotton-blend',
  'Plastic/ Metal/ Fabric',
  'Microfibre',
  'Blend (with shimmer)',
  'Leather/ Canvas/ Synthetic Materials',
  'Crepe',
  'Spandex/ Nylon/ Cotton/ Polyester',
  'Satin blend',
  'Sequin fabric',
  'Rayon',
  'Cotton/ Silk/ Polyester/ Rayon',
  'Denim/ Cotton',
  'Soft',
  'Plastic',
  'Lace and fabric blend',
  'Blended fabric',
  'Smooth fabric',
  'Lace and jersey',
  'Rubber/ EVA',
  'Lightweight knit',
  'Cotton/ Terry/ Wool',
  'Lace',
  'Chiffon',
  'Nylon blend',
  'Fabric',
  'Fabric (may include cotton or a similar blend)',
  'Cotton/ Polyester/ Denim/ Linen',
  'Wool/ Cotton/ Polyester/ Linen',
  'Organic cotton',
  'Lightweight fabric',
  'Blend of lace and sheer fabric',
  'Denim/ Leather/ Wool/ Nylon/ Polyester',
  'Cotton/ Linen/ Jersey/ Polyester',
  'Cotton/ Linen/ Polyester/ Silk',
  'Stretch cotton',
  'Generic',
  'Blend',
  'Synthetic',
  'Jersey knit',
  'Viscose blend',
  'Cotton blend with lace',
  'Stretch fabric',
  'Fabric (cotton or similar)',
  'Polyester/ Spandex/ Nylon',
  'Ribbed cotton',
  'Nylon/ Polyester/ Wool',
  'Elastic',
  'Waffle knit',
  'Metal/ Leather/ Beads',
  'Knit fabric',
  'Cotton/ Wool/ Nylon/ Polyester',
  'Ribbed knit',
  'Silk blend',
  'Leather/ Canvas/ Mesh/ Synthetic',
  'Wool/ Cotton/ Polyester',
  'Metal/ Plastic',
  'Knit',
  'Wool/ Cashmere/ Silk/ Cotton',
  'Cotton/lace',
  'Leather/ Canvas/ Nylon',
  'Rayon and lace',
  'Metallic blend',
  'Sheer and opaque blend',
  'Elastic/ Cotton',
  'satin',
  'silk',
  'Cotton',
  'Strawberry',
  'Denim',
  'Lightweight cotton',
  'Cotton/ Polyester/ Silk/ Rayon',
  'Cotton/ Spandex/ Nylon',
  'Blend (possibly cotton or modal)',
  'Fabric (likely cotton or blend)',
  'Beaded fabric',
  'Viscose',
  'Plastic/ Metal',
  'polyester',
  'Cotton, lace',
  'Chiffon, lace',
  'Cotton and mesh',
  'Light fabric',
  'Sheer fabric',
  'Silk-like fabric',
  'Fabric (possibly blended)',
  'Various',
  'Silky',
  'Synthetic fibers',
  'Knit cotton',
  'Cotton/ Polyester/ Silk/ Chiffon/ Linen',
  'Lace and spandex',
  'leather',
  'Nylon/spandex',
  'Chiffon and jersey',
  'Polyester',
  'Cotton/ Jersey/ Polyester',
  'Various/ depending on items in the set',
  'Stretchy fabric',
  'Jersey with lace',
  'Cotton and sheer fabric',
  'Satin (with lace)',
  'Various/ depending on type',
  'Lace and mesh',
  'Satin',
  'Woven fabric',
  'Silk or satin',
  'Jersey fabric',
  'Silk',
  'Cotton/ Linen/ Denim/ Polyester',
  'Straw/ Cotton/ Wool',
  'Stretch knit',
  'Cotton blend',
  'Mesh',
  'Velvet and mesh',
  'Textured fabric',
  'Nylon',
  'Sparkly fabric',
  'Knitted fabric',
  'Nylon/ Spandex/ Cotton',
  'nylon',
  'Cotton/ Polyester/ Linen/ Wool',
  'Ribbed fabric',
  'Acrylic blend',
  'Mesh and jersey',
  'Cotton/ Linen/ Wool/ Polyester',
  'Sequins',
  'Leather/ Rubber/ Canvas',
  'Synthetic blend',
  'Metal',
  'Leather and cotton blend',
  'Nylon/ Spandex/ Polyester',
  'Polyester/Nylon',
  'cotton',
  'Cotton and lace',
  'Polyester',
  'Fabric (cotton blend)',
  'Nylon/Polyester',
  'Leather',
  'Sheer',
  'Cotton/ Nylon/ Spandex',
  'denim',
  'Rayon blend',
  'Linen',
  'Detergent',
  'Polyester blend',
  'Soft fabric',
  'Chiffon blend',
  'Cotton/ Fleece/ Polyester',
  'wool',
  'Leather/ Suede/ Canvas',
  'linen',
  'Leather/ Canvas/ Synthetic',
  'Nylon/ Polyester/ Cotton Blend',
  'Cotton/ Polyester/ Pique',
  'Fleece',
  'Sequin',
  'Velvet',
  'Leather/ Suede/ Synthetic Materials',
  'Wool/ Polyester/ Cashmere/ Nylon',
  'Wool/ Cashmere/ Cotton/ Acrylic',
  'Wool/ Cashmere/ Acrylic/ Cotton',
  'Fabric with sequins',
  'Sheer, synthetic',
  'Jersey',
  'lace',
  'Cotton',
];

export const VALID_PATTERNS = [
  'Chain and geometric',
  'Color-blocked',
  'Other pattern',
  'Abstract',
  'Embroidery',
  'Chambray',
  'Plaid',
  'Mixed media',
  'Slub',
  'Branding/text',
  'Stripes',
  'Unknown',
  'Graphic text',
  'Floral graphic',
  'Graphic/print',
  'Stripe',
  'Logo stripe',
  'Baroque and leopard print',
  'Color block, animal print',
  'Eyelet',
  'Lace',
  'Illustration',
  'Striped accents',
  'Dotted',
  'Heart',
  'Leopard',
  'Mixed',
  'Artistic',
  'Line art',
  'Transparent',
  'Gradient',
  'Leaf',
  'Solid',
  'Dots and stars',
  'Colorblock',
  'Heathered',
  'Logo print',
  'Contrast',
  'Lace detail',
  'Floral eyelet',
  'None',
  'Color-block',
  'Snakeskin',
  'Text/graphic',
  'Embroidered',
  'Textual',
  'Solid with lace accents',
  'Dot',
  'Logo',
  'Graphic design',
  'Text',
  'All over pattern',
  'Abstract leopard',
  'Knitted',
  'Denim',
  'Dots',
  'Hologram',
  'Tropical',
  'Animal print',
  'Open weave',
  'Chevron',
  'Paisley',
  'Leopard print',
  'Graphic/printed',
  'Solid with stripes',
  'Barbed wire',
  'Floral lace',
  'Neps',
  'Zigzag stripes',
  'Textured',
  'Mixed prints',
  'Speckled',
  'Abstract nature',
  'Graphic print',
  'Solid with lace',
  'Waffle',
  'Solid',
  'Front print',
  'Polka dots',
  'Illustrative',
  'Embellished',
  'Striped',
  'Feathers',
  'Print',
  'Text and illustration',
  'Mesh',
  'Solid with contrast trim',
  'Metallic',
  'Printed',
  'Placement print',
  'Floral/polka dot',
  'Marble',
  'Abstract grid',
  'Sequins',
  'Application/3D',
  'Mixed print',
  'Jacquard',
  'Solid with embroidered detailing',
  'Animal',
  'Treatment',
  'Gingham',
  'Ornate print',
  'Glittering/Metallic',
  'Ruffled',
  'Abstract lines',
  'Geometric',
  'Pleated',
  'Floral',
  'Check',
  'Stars',
  'Graphic',
  'Flame',
  'Color block',
  'Ribbed',
  'Open knit',
  'Dot/spotted',
  'Illustrated',
  'Polka dot',
  'Camouflage',
  'Fish',
  'Logo/text',
  'Other structure',
  'Bandana',
  'Tie-dye',
  'Lace trim',
  'Butterfly',
  'Mandala',
  'Colour blocking',
  'Cactus',
  'Cactus print',
  'Argyle',
  'Chain',
  'Plain',
  'Melange',
  'Sequin',
  'Floral and animal print',
  'Mixed solid/pattern',
  'Logo print',
];
