# Generated by Django 5.1.2 on 2024-10-16 21:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('vector', pgvector.django.vector.VectorField(dimensions=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='image_search.imageinfo')),
            ],
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_search.productinfo'),
        ),
    ]
