name: CICD

on:
  push:
    branches:
      - d23124670_pavan

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        working-directory: ./smartwardrobe-frontend
        run: docker build -t d23124670/smartwardrobe-frontend .
      - name: Publish image to docker hub
        run: docker push d23124670/smartwardrobe-frontend:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull d23124670/smartwardrobe-frontend:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer d23124670/smartwardrobe-frontend:latest
      - name: Copy container to ec2
        run: sudo docker cp reactContainer:/usr/share/nginx/html /usr/share/nginx/
      - name: Update Nginx configuration for HTTPS
        run: |
          # Ensure Nginx is reloaded to apply changes
          sudo systemctl restart nginx
          # Optional: Reload Nginx to apply changes
          sudo systemctl reload nginx
      - name: Verify HTTPS Deployment
        run: |
          curl -I https://smartwardrobe.store
